migrated Cone.ts, RayIntersect.ts and fixed some problems with the pr…
dioxygen-software/three-examples pull request #5
Opened 2024-05-28 12:23 UTC by matteoJeulin

Migrated Cone.ts, RayIntersect.ts and ConeFrustum.ts

2024-05-29 12:12 UTC, ersbeth requested changes

2024-05-29 12:12 UTC, ersbeth commented on src/geometries/coneFrustum/ConeFrustum.ts
> +    static computeOptimisedDownscalingBoundingCube( center0: Vector3, radius0: number, center1: Vector3, radius1: number, origin: Vector3, minScale: number ): Float32Array {
Origin may be null

2024-05-29 12:12 UTC, ersbeth commented on src/geometries/coneFrustum/ConeFrustum.ts
> +    /**
remove unused comments

2024-05-29 12:12 UTC, ersbeth commented on src/geometries/coneFrustum/ConeFrustum.ts
Put back optional parameters, minscale = 0.5 as default value

2024-05-29 12:12 UTC, ersbeth commented on src/geometries/coneFrustum/ConeFrustum.ts
> +        if ( origin != null ) {
Change to if (origin) because origin is vector3 or undefined, but not null

2024-05-29 12:12 UTC, ersbeth commented on src/geometries/coneFrustum/ConeFrustum.ts
> +        return attribute.array as Float32Array;
don't cast here because we are not sure this is Float32Array inside

2024-05-29 12:20 UTC, ersbeth requested changes

2024-05-29 12:20 UTC, ersbeth commented on src/geometries/spheres/RoundedCubeBufferGeometry.ts
> +            throw "cubeBufferGeometry has null index attribute."
Put a more explicit message:
"[RoundedCubeBufferGeometry] CubeBufferGeometry shouldn't have a null index attribute."

2024-05-29 12:20 UTC, ersbeth commented on src/geometries/spheres/SpherifiedCubeBufferGeometry.ts
> +            throw "cubeBufferGeometry has null index attribute."
Put a more explicit message as above

2024-05-29 12:55 UTC, maximeq commented on src/geometries/coneFrustum/ConeFrustum.ts
> +        return attribute.array as Float32Array;
Never cast in general, prefer patterns like:
```
if (attribute.array instanceof Float32Array) {
   return attribute.array;
} else {
  throw new Error("The returned array is expected to be a Float32Array");
}
```

If you don't want to throw to avoid crashing up the whole user program, then:
```
console.error("..");
return new Float32Array(... filled with some standard default value ...);
```

2024-05-31 11:52 UTC, ersbeth requested changes

2024-05-31 11:52 UTC, ersbeth commented on src/materials/MeshWorldNormalMaterial.ts
> +            const new_mat = this.material;
Why did you add "new_mat" ?

2024-05-31 11:52 UTC, ersbeth commented on src/math/coneFrustum/ConeFrustum.ts
> +        if (attribute.array instanceof Float32Array) {
Prefer the following pattern, whithout "else" branch.
```
if (check is wrong) throw error;
return result;
```

This is more readable, and you can chain multiple checks/throws if needed

2024-05-31 11:52 UTC, ersbeth commented on src/modifiers/EdgeSplitModifier.ts
> +					attribute.array = attributeArray; // This is a hack to update the attribute array
However this code used to work before, why is it indicated as readonly by TS ?

2024-05-31 11:52 UTC, ersbeth commented on src/modifiers/EdgeSplitModifier.ts
> +							geometry.attributes.normal = new BufferAttribute(attributeArray, geometry.attributes.normal.itemSize, geometry.attributes.normal.normalized);
Same as above.

2024-05-31 11:58 UTC, ersbeth commented
@matteoJeulin please update the README with the new folder structure. I see that the title is wrong too, it needs to be updated to the repo's name.

2024-06-03 12:15 UTC, ersbeth requested changes

2024-06-03 12:15 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +                "three/examples/jsm/utils/BufferGeometryUtils.js": "../node_modules/three/examples/jsm/utils/BufferGeometryUtils.js"
Load the three example directly from node_modules and remove the files in js/ folder

2024-06-03 12:15 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +        import { OrbitControls } from './js/OrbitControls.js';
Same as above

2024-06-03 12:15 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +        import { GUI } from './js/lil-gui.module.min.js';
Replace this with dat-gui to avoir multiple GUI frameworks

2024-06-04 12:32 UTC, ersbeth requested changes

2024-06-04 12:32 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +                "three/examples/jsm/utils/BufferGeometryUtils.js": "../node_modules/three/examples/jsm/utils/BufferGeometryUtils.js",
You don't need this one because it is covered by the three/ import above

2024-06-04 12:32 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +        import { BufferGeometryUtils } from '../node_modules/three/examples/jsm/utils/BufferGeometryUtils.js';
Don't load it from `../node_modules` but with a bare import as in previous lines. The import map is already responsible for resolution against `node_module`.

2024-06-04 12:32 UTC, ersbeth commented on tests/modifiers.edge-split-modifier.test.three-js-test.html
> +        import { GUI } from 'dat.gui';
Hum I don't think this is enough at all. Did you try to execute this ? These are different libraries, the idea was to replace lil with dat to have only one GUI lib in all examples. This should involve updating the GUI code to perform in similar way but with the orther lib.

2024-06-07 14:40 UTC, merged